### ISSUE TITLE
manual/scalaGuide/main/global/ScalaInterceptors.md

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#1003]
- https://github.com/playframework-ja/translation-project/tree/2.3.5/manual/scalaGuide/main/global/ScalaInterceptors.md
- diffs between [2.2.0/manual/scalaGuide/main/global/ScalaInterceptors.md](https://github.com/playframework-ja/translation-project/tree/2.2.0/manual/scalaGuide/main/global/ScalaInterceptors.md) and [2.3.5/manual/scalaGuide/main/global/ScalaInterceptors.md](https://github.com/playframework-ja/translation-project/tree/2.3.5/manual/scalaGuide/main/global/ScalaInterceptors.md).

```
--- /Users/garbagetown/Desktop/2.2.0/manual/scalaGuide/main/global/ScalaInterceptors.md 2013-09-19 10:11:22.000000000 +0900
+++ //Users/garbagetown/Desktop/2.3.5/manual/scalaGuide/main/global/ScalaInterceptors.md    2014-07-28 12:26:38.000000000 +0900
@@ -1,3 +1,4 @@
+<!--- Copyright (C) 2009-2013 Typesafe Inc. <http://www.typesafe.com> -->
 # Intercepting requests

 ## Using Filters
@@ -32,4 +33,4 @@
 It’s also possible to intercept a specific Action method, using [[Action composition | ScalaActionsComposition]].


-> **Next:** [[Testing your application | ScalaTest]]
\ No newline at end of file
+> **Next:** [[Testing your application | ScalaTestingYourApplication]]

```

**Comment by wm3** [comment]
実質的な変更が無いのでレビュー無しでマージしました。
