### ISSUE TITLE
manual/gettingStarted/Modules.md

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#1198]
- https://github.com/playframework-ja/translation-project/tree//2.4.x/manual/gettingStarted/Modules.md

**Comment by tango238** [comment]
やりますー。

**Comment by garbagetown** [comment]
ありがとうございます。遅くなりましたがマージしました！

あと一箇所だけ翻訳漏れがあったので 0245d0ba6dd6f4fd6654aa6c1122d27c35a8553b で対応しました。ご確認ください :smiley:
