### ISSUE TITLE
manual/working/scalaGuide/main/forms/ScalaCustomFieldConstructors.md

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#1281]
- https://github.com/playframework-ja/translation-project/tree//2.4.x/manual/working/scalaGuide/main/forms/ScalaCustomFieldConstructors.md

**Comment by 12345** [comment]
やります！

**Comment by garbagetown** [comment]
backport to
- [ ] 2.2.x
- [ ] 2.3.x

**Comment by garbagetown** [comment]
backport to
- [ ] 2.2.x #821
- [ ] 2.3.x #998
