### ISSUE TITLE
manual/working/scalaGuide/main/forms/ScalaCustomValidations.md

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#1282]
- https://github.com/playframework-ja/translation-project/tree//2.4.x/manual/working/scalaGuide/main/forms/ScalaCustomValidations.md

**Comment by 12345** [comment]
やります！

**Comment by garbagetown** [comment]
backport to
- [ ] 2.2.x
- [ ] 2.3.x

**Comment by garbagetown** [comment]
backport to
- [ ] 2.2.x #999
- [ ] 2.3.x #822
