### ISSUE TITLE
manual/working/scalaGuide/main/json/ScalaJsonHttp.md

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#1295]
- https://github.com/playframework-ja/translation-project/tree//2.4.x/manual/working/scalaGuide/main/json/ScalaJsonHttp.md

**Comment by 12345** [comment]
やります！

**Comment by garbagetown** [comment]
backport to
- [ ] 2.3.x

**Comment by garbagetown** [comment]
backport to #1016
