### ISSUE TITLE
replace images link

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#139]
in order to reduce the size of packaged war file, replace all images link to browse original url.

**Comment by wm3** [comment]
横槍ですが、一応意見を…。

外部サイトに依存するとリンク切れや今のバージョンと矛盾してしまう事が起きたりしないでしょうか?

依存性を減らすことを考えると、自前で持った方が良いんじゃないかと思ったりはします。

**Comment by garbagetown** [comment]
まず背景ですが、google app engineには100MBを超えるアプリケーションをデプロイできないという制限があります。

この制限に引っ掛かった際、容量のほとんどを占めていたのが重複する画像ファイルだったため、playdocjaにはリクエストされた画像ファイルが見つからない場合、他のバージョンの画像ファイルを探しに行く機能を追加し、重複する画像ファイルを削除しました。

これに関連して、いっそ画像ファイルをすべて削除して本家のサイトを参照するようにしようと考えました。

続いて対応予定ですが、容量制限に再度引っ掛かるまでは延期することができます。また、100MBの制限がない環境に移行できれば対応の必要はありません。

最後に依存性ですが、現在もトップページのニュース欄やダウンロードページなど、本家サイトを都度スクレイピングしてパースしている箇所があります。

以上より、今後、下記について議論して対応方針を決定したいと思います。
1. google app engineから別の環境に移行するか否か
2. 本家サイトへの依存の是非と非の場合の代替策

**Comment by wm3** [comment]
なるほど。背景と依存性の件、了解しました。

**Comment by garbagetown** [comment]
翻訳プロジェクトが本家に取り込まれる運びとなり、本 issue に対応する必要がなくなりました。
