### ISSUE TITLE
ScalaJsonGenericsの翻訳

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#148]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/scalaGuide/main/json/ScalaJsonGenerics.md

**Comment by mumoshu** [comment]
翻訳しました。
https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/scalaGuide/main/json/ScalaJsonGenerics.md

**Comment by mumoshu** [comment]
レビューって必要ですか？

**Comment by garbagetown** [comment]
必要ないと思います。ばんばんリリースしてどんどん直しましょう。とくに気になるところがなければ、ご自身でissueをクローズしてください。

**Comment by mumoshu** [comment]
ですよね！
また気になる点が出てきたら、issueを切りなおすなりしようと思います。
