### ISSUE TITLE
Evolutionsの翻訳

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#149]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/detailledTopics/evolutions/Evolutions.md

**Comment by mumoshu** [comment]
翻訳しました。
https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/detailledTopics/evolutions/Evolutions.md

**Comment by wm3** [comment]
レビューしました。特におかしな所は見つかりませんでした。

自然で読みやすい、と思います。
