### ISSUE TITLE
Configuration の翻訳

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#150]

**Comment by mumoshu** [comment]
翻訳しました。
https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/detailledTopics/configuration/Configuration.md

**Comment by wm3** [comment]
「置換」の前まで確認しました。

全体的には読みやすく書かれている、と思いました。ただ、若干間違っていそうな部分があったので書いておきます。

#### 1 代替設定ファイルの指定

原文:
config.resource specifies a resource name - not a basename, i.e. application and not application.conf

```
- * `config.resource` はリソースファイルの指定です - application のようなベースネームの指定はできません。また、 application.conf 以外を指定します。
+ * `config.resource` はリソースファイルの指定です。ベース名は使用できません - つまり application ではなく application.conf となります。
```

意図としては単純に「拡張子が入ります」という意味で、「application.conf を指定しない」という事は書かれていないように読めました。

一応 start スクリプトを実行して確認したところ、拡張子は必要、application.conf の指定は可能 (もちろん普通は指定する必要はありませんが…) でした。

ただし、原文を見ると逆の事を書いているようにも見えます。…正直な所、判断が難しい所です。

#### 2 root の括弧の省略

原文:
A HOCON file is invalid if it omits the opening { but still has a closing }; the curly braces must be balanced.

```
- しかし、始め中括弧 `{` があるにも関わらず 閉じ中括弧 `}` が存在しないようなファイルは HOCON フォーマットとして正しくありません。中括弧はバランスされている必要があります。
+ しかし、始め中括弧 `{` を省略したにも関わらず 閉じ中括弧 `}` が存在するようなファイルは HOCON フォーマットとして正しくありません。中括弧はバランスされている必要があります。
```

間違った事は言っていないのですが、挙げている例の説明は逆ではないかと思います。

**Comment by wm3** [comment]
一つ目の方を #208 の pull request にしてみました。
