### ISSUE TITLE
JavaHome から OAuth へのリンク削除

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#174]
http://www.playframework.org/documentation/2.0.2/JavaHome
本家の2.0.2にはJava版のOAuthのページはないようです。

**Comment by garbagetown** [comment]
申し訳ありませんが issue の内容を掴みかねています。なにを直せばよいですか？

**Comment by mumoshu** [comment]
忘れてください！

Java版のドキュメントには存在しないはずのOAuthのページへのリンクが入ってしまっている、
という意味のissueだったのですが、今確認してみたところ問題ありませんでした。
勘違いだと思います。

**Comment by garbagetown** [comment]
了解しました :smiley:
