### ISSUE TITLE
JavaCache 翻訳

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#180]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/javaGuide/main/cache/JavaCache.md

**Comment by mumoshu** [comment]
翻訳しました。

**Comment by wm3** [comment]
お疲れさまです。レビューしました。

 ヘッダが認識されていないようでしたので、直してみました。
その他変なところは無いと思います。

**Comment by wm3** [comment]
ちなみに、翻訳そのものの事ではありませんが、翻訳されたページが 2.0.2 以下になっています。 2.0.3 は英語のままなのですが、意図されてそうしていたりしますか?

**Comment by mumoshu** [comment]
ありがとうございます！
ところどころtranslatedタグを間違えていたので、修正しないとだめですね・・。

> ちなみに、翻訳そのものの事ではありませんが、翻訳されたページが 2.0.2 以下になっています。 2.0.3 は英語のままなのですが、意図されてそうしていたりしますか?

はい。2.0.2を翻訳の翻訳が終わってから、2.0.3の翻訳へ移ろうと思っています。
その理由ですが、旧バージョンのドキュメントもplaydocjaで提供し続けると思うので翻訳が必要だということ、また2.0.3の翻訳を効率的にすすめるためです。

後者について補足すると、2.0.3のドキュメントは2.0.2とあまり変更がないそうです。
そのため、2.0.3をゼロから翻訳するよりも、変更がない部分は2.0.2の翻訳内容を機械的にコピペしてから、差分を翻訳したほうが効率的だと考えています。
その理由もあって、兎にも角にも、2.0.2をまず翻訳している状態です。

**Comment by wm3** [comment]
了解しました。では、こちらでも 2.0.2 から修正する事にします。
