### ISSUE TITLE
JavaActionsComposition 翻訳

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#185]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/javaGuide/main/http/JavaActionsComposition.md

**Comment by wm3** [comment]
レビューしました。

内容的に気になる点が二つほどありました。

#### 1. 「Play builds a root action for you that just calls the proper action method」の部分

「Playは、上記の方法で定義されたアクションメソッドを呼び出すルートアクションを自動的に生成してくれます」という風に訳されていますが、「上記の方法で定義されたアクションメソッド」というのが読んでて気になりました。

具体的には、「上記の方法」が上のコードブロック(public abstract class Action { ... })の事を指しているように読めてしまうのではないかと思いました。

僕の解釈が正しければ、「action method」は以前の節や「アクションのおさらい」の部分で「Controller クラスの static method」という風に説明されていたと思います。

ですので、「上記の方法で定義された」は特に必要無いのではないかと思っています。

#### 2. 「You also mix with several:」の部分

上記の部分の訳が抜けてしまっているように見受けられました。
