### ISSUE TITLE
JavaXmlRequests 翻訳

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#197]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/javaGuide/main/xml/JavaXmlRequests.md

**Comment by wm3** [comment]
翻訳しました。

**Comment by mumoshu** [comment]
全体的に良い感じでした！
細かいニュアンスできになるところがあったので、ぷるりしました。
よろしければマージをお願いします。

**Comment by wm3** [comment]
ありがとうございます！

**Comment by garbagetown** [comment]
内容を確認しました。

> このアクションは、コマンドラインから cURL を使って以下のようにテストできます。

の cURL は curl の誤字のような気もしますが、原文ママなのでこのまま行きましょう。

**Comment by masahitojp** [comment]
> このアクションは、コマンドラインから cURL を使って以下のようにテストできます。

curlの公式サイトも"cURL”としているので原文もこの書き方で正しいのだと思います。
(このサイト内でも"curl", "cURL", "Curl"が混在しているのであんまりポリシーないのかも :-) )

http://curl.haxx.se/

**Comment by garbagetown** [comment]
curl コマンドはときどき使っていましたが公式サイトを確認したことはありませんでした。情報ありがとうございます！
