### ISSUE TITLE
JavaTodoList 翻訳

### ISSUE THREAD

**Issue by wm3** [playframework-ja/translation-project#203]
issue が見当たらなかったので追記しておきます。

https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.2/manual/javaGuide/tutorials/todolist/JavaTodoList.md

**Comment by wm3** [comment]
もしよろしければ、着手しちゃいます。

**Comment by garbagetown** [comment]
おねがいします！

**Comment by garbagetown** [comment]
ばっちりだと思います。誤字らしきところだけ変更しました
