### ISSUE TITLE
Cometソケットの誤字

### ISSUE THREAD

**Issue by tarchan** [playframework-ja/translation-project#209]
誤字の報告です。

https://playdocja.appspot.com/documentation/2.0.2/JavaComet

誤：一つのチャンクにつき、JavaSCriptを含む
正：一つのチャンクにつき、JavaScriptを含む

**Comment by wm3** [comment]
ご指摘ありがとうございます！

ソースの方の修正はしましたが、サイトの方に反映されるのはもう少し時間がかかると思われますので、しばらくお待ちください。
