### ISSUE TITLE
playframework-ja.org w/o www. prefix

### ISSUE THREAD

**Issue by wm3** [playframework-ja/translation-project#218]
翻訳の誤りと言うよりサイトに関するリクエストですが…。

新サイト(playframework-ja.org)に直打ちでドメインを打つと、頭のwww.がないために見つからないことがあります。ブラウザ側でwww.を入れてくれることもあるのですが、してくれないこともあり、「落ちているのかな?」と心配してしまうことがあります。

できればwww.無しにリダイレクトするか、サイトをwww.なしのドメインで提供してくれたらなあ、などと思うのですが、いかがでしょうか?

**Comment by garbagetown** [comment]
google appenginのアプリを独自ドメインで公開する場合、サブドメイン無しのURLが設定できないんです。

無料で使えてplay 1.x系が動いてwww無しの独自ドメインを公開できる環境があれば引越します。どこかご存知ないですか？

**Comment by wm3** [comment]
なるほど、こちらでも少し調べてみます…。
