### ISSUE TITLE
2.0.4 ScalaJsonRequests, ScalaJsonGenerics Page Not Found

### ISSUE THREAD

**Issue by yoyama** [playframework-ja/translation-project#219]
こちらの翻訳サイト大変参考にさせていただいています。
以下のページ自体が存在しないようでしたので報告させてもらいます。

http://www.playframework-ja.org/documentation/2.0.4/ScalaJsonRequests
http://www.playframework-ja.org/documentation/2.0.4/ScalaJsonGenerics

よろしくお願いします。

**Comment by wm3** [comment]
報告ありがとうございます！

以前のバージョンのページはあるようですので、しばらくはこちらを見てもらえばと思います。

http://www.playframework-ja.org/documentation/2.0.3/ScalaJsonRequests
http://www.playframework-ja.org/documentation/2.0.3/ScalaJsonGenerics

**Comment by yoyama** [comment]
あ、2.0.3 のがあったのですね。
ありがとうございます。
読ませて頂きます。

**Comment by garbagetown** [comment]
リリース誤りが原因でした。対応しましたのでご確認ください。
