### ISSUE TITLE
Production.md

### ISSUE THREAD

**Issue by wshino** [playframework-ja/translation-project#220]
細かいのですが…

https://github.com/garbagetown/playdocja/blob/master/documentation/2.0.4/manual/detailledTopics/production/Production.md

もし Play がサーバにインストールされていないのだえれば、同じことを行うために sbt を使ってもよいでしょう。

↓

もし Play がサーバにインストールされていないのであれば、同じことを行うために sbt を使ってもよいでしょう。

**Comment by wm3** [comment]
ご指摘ありがとうございます！該当箇所を修正しました。反映されるのはもう少しかかりますので、しばらくお待ちください。

**Comment by garbagetown** [comment]
ご指摘と修正ありがとうございます。リリースしましたのでご確認ください。

http://www.playframework-ja.org/documentation/2.0.4/Production

**Comment by wshino** [comment]
$B3NG'$7$^$7$?!#BP1~$"$j$,$H$&$4$6$$$^$9(B

2013$BG/(B1$B7n(B10$BF|LZMKF|(B yuichiro umezawa notifications@github.com:

**Comment by garbagetown** [comment]
申し訳ありませんがお返事の内容が文字化けしていて分かりません。よろしければ再度お返事ください。

**Comment by wshino** [comment]
メールに返信すると文字化けするようですね。失礼しました。
内容は以下のとおりです。
---- 8< ----
確認しました。対応ありがとうございます
