### ISSUE TITLE
ボディーパーサーの誤字

### ISSUE THREAD

**Issue by aoiroaoino** [playframework-ja/translation-project#222]
誤字報告です。

http://www.playframework-ja.org/documentation/2.0.2/ScalaBodyParsers

三段落目、Iteratee内のString
誤：計算された String を結果として返します(Iteratee[Array[Byte],STring])。
正：計算された String を結果として返します(Iteratee[Array[Byte],String])。

同様の誤字が2.0.3と2.0.4にもありました。

**Comment by wm3** [comment]
ありがとうございます！修正しました。反映されるまではもうしばらくお待ちください。

**Comment by garbagetown** [comment]
リリースしました。ご確認よろしくお願いします。
