### ISSUE TITLE
about ページリンク切れ

### ISSUE THREAD

**Issue by wm3** [playframework-ja/translation-project#223]
トップページのヘッダから「About」ページをクリックすると、エラーになります。

http://www.playframework-ja.org/about

**Comment by garbagetown** [comment]
返信遅くなってすみません。

aboutページは、githubクライアントライブラリを使ってgithubのplaydocjaからcollaboratorの情報を取ってきて動的に表示しているのですが、appengineの中でNullPointerExceptionが発生しているようです。

appenginかgithub APIの仕様が何か変わったのではないかと思います。週末に調査しますのでしばらくお待ちください。

**Comment by garbagetown** [comment]
githubクライアントのバージョンを2.0.1から2.1.3に上げたらNullPointerExceptionは発生しなくなりましたが、動作確認のためにばんばんアクセスしていたらorg.eclipse.egit.github.core.client.RequestExceptionとかいう例外が出てしまいました。API使用回数の閾値超過のようです。
aboutページもprodモードでは動的に生成しないよう仕掛けが必要ですね。対応するのでしばらくお待ちください。

**Comment by garbagetown** [comment]
一時間当たり5000リクエストまでAPIを叩けるようOAuth認証を追加します

**Comment by garbagetown** [comment]
今のところ動いているので 2.1 での対応は見送り master に棚上げします

**Comment by garbagetown** [comment]
we don't need to deal with this issue any more coz the translations come to be included to playframework.com, and there aren't the about page.
