### ISSUE TITLE
Play 2.1

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#224]
ここ数日、ドキュメントの変更が多くなってきたのでそろそろ来たりして・・・。

https://github.com/playframework/Play20/commits/master

**Comment by garbagetown** [comment]
RC-3とRC-4の間隔がすごく短かったのでそろそろ出そうですね。正式リリースされたらドキュメントの差分をチェックしてissueばんばん起こしておきます。

**Comment by ikeike443** [comment]
$BAa$1$l$P:#=5$N?eMK$@$H;W$$$^$9(B

2013$BG/(B2$B7n(B4$BF|(B 5:21 yuichiro umezawa notifications@github.com:

**Comment by masahitojp** [comment]
RC4の今の段階でissueを起こし始めませんか？リリースに向けて、変更されるドキュメントは増えることはあっても減ることはないと思いますー

**Comment by ikeike443** [comment]
すっげー文字化けしてた。。

チームのML見る限り早ければ今週水曜に出ますけど、どうかな。。ちょっと遅れるんじゃないでしょうか。

**Comment by garbagetown** [comment]
池田さん
情報提供ありがとうございます！
issueのメールにはreply to this emailとか書いてありながら返信すると文字化けしてしまうようです :-(

中村さん
RC3とRC4でドキュメントの差分は1ファイルだけでしたので、ほぼ固まったと見て問題ないでしょうね。
今晩中を目途にissue起こしてしまいます。途中で力尽きたら続きをお願いします :-)

**Comment by masahitojp** [comment]
To garbagetown

いいですよ:-) 
2.0.4と2.1RC4をdiffって、変更されるファイルのリストをとってissueに上げとけばいいんですよね?

**Comment by masahitojp** [comment]
2.0.4と2.1RC4をdiffって変更されたファイルをIssueに追加しました

https://github.com/garbagetown/playdocja/issues?labels=2.1&milestone=&page=1&state=open
https://github.com/garbagetown/playdocja/issues?milestone=7&state=open

現状107Issueが追加されてますよ。(_Sidebar.mdはまとめて1issueにしました)

**Comment by masahitojp** [comment]
Issueに登録されているURLは "https://github.com/garbagetown/playdocja/blob/master/documentation/2.1/ …***" みたいにgithubに登録されていない"2.1"フォルダを指していますので、リンクをクリックすると404になります。
本物のファイルが登録された後に、調整が必要かもしれません。

**Comment by ikeike443** [comment]
んー、なんか出そうですよ。もうブロッカーバグなくなったっぽい。

**Comment by garbagetown** [comment]
中村さん
鬼のようにissue登録メールが来てビビりました。対応ありがとうございます！

池田さん
おお！そうすると明後日あたりですかね。正式に出たらオリジナルドキュメントをplaydocjaに突っ込んでpushします。

各位
2.1用のブランチは既に切ってあるのでpullしてください:-)

**Comment by mumoshu** [comment]
皆さんありがとうございます！
早速2.1ブランチをぷるっておきました。

**Comment by masahitojp** [comment]
2.1.0がついにリリースされましたね！Webページのデザイン、ドメイン(!)がかわってますね
2.1-RC4/2.1.0とのドキュメントをdiffった結果から、Issueを追加しときました。
新しく4ファイル分が更新されてますね。

> To 梅澤さん

そろそろこのIssueは閉じてもいいかも

**Comment by garbagetown** [comment]
2.1の未翻訳ドキュメントをbranchにaddしてpushしました。pullしたらissueにご自身をassignして翻訳してください。早い者勝ちです :smiley: 
2.0.4から差分のないドキュメントについては今週中を目処に私が反映しておきます。

本家サイトのデザインが大きく変わったので、私はこの変更反映作業に注力します。翻訳作業についてご協力頂ければと思います。よろしくお願いいたします。
