### ISSUE TITLE
RequireJS-support.mdの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#231]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/detailledTopics/assets/RequireJS-support.md

**Comment by wm3** [comment]
このページの翻訳、作業中だったりしますでしょうか？

もし問題なければ巻取れればと思いますが、どうでしょう？

**Comment by masahitojp** [comment]
手元で半分ほど翻訳してありますので、明日までに翻訳して上げておきます。

ご心配をかけてすみません。

**Comment by garbagetown** [comment]
@masahitojp さん、こちらの状況いかがですか？お忙しいようでしたら、作業途中でも構いませんのでpushして頂ければ巻き取ります。

**Comment by masahitojp** [comment]
作業が遅れて本当にすいません。

**Comment by masahitojp** [comment]
@garbagetown さんからのレビュー結果を受けて、reopen

**Comment by masahitojp** [comment]
- 半角スペース
- 誤字
- 原文にあるリンクや装飾が無くなっている
- 原文で改行されていないのに訳文で改行されている
- コメントアウトした原文のあと無意味な空行を挟んで訳文を書いているところです

**Comment by masahitojp** [comment]
指摘箇所を修正しました。 @garbagetown さんレビューをお願いします。

**Comment by garbagetown** [comment]
#405 で空白と改行、句読点について些細な pullreq を送りました。確認して問題なければマージしてください。

その他、訳文の内容について気になった点を e870342 にコメントしました。一部、私もよく分からないところがあるので、 @wm3 さんにもご協力頂きながら完成したいと思います。

**Comment by masahitojp** [comment]
レビュー結果をpushしました。すいません、コメント欄のissue 番号を間違えてしまいました

**Comment by garbagetown** [comment]
確認しました。問題ないと思います :smiley:
