### ISSUE TITLE
Build.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#232]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/detailledTopics/build/Build.md

**Comment by wm3** [comment]
翻訳しました。2.0.4 のままの部分が多いですが、若干翻訳もしましたので @garbagetown さんレビューお願いします!

**Comment by garbagetown** [comment]
LGTM :thumbsup:
