### ISSUE TITLE
SBTSubProjects.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#235]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.1/manual/detailledTopics/build/SBTSubProjects.md

**Comment by wm3** [comment]
新規の部分がありますので、レビューをお願いします。m(__)m レビューは @mumoshu さんで!

**Comment by garbagetown** [comment]
@mumoshu さん、こちらも確認よろしくお願いします。

**Comment by mumoshu** [comment]
遅くなりましたがレビューしました。
特に指摘事項等ありません。ナイス翻訳です！

**Comment by mumoshu** [comment]
この関連コミットはもう取り込まれてますよね？
クローズしちゃいますね

**Comment by garbagetown** [comment]
早！azs!!
