### ISSUE TITLE
Evolutions.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#239]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/detailledTopics/evolutions/Evolutions.md

**Comment by wm3** [comment]
翻訳しました。

新規の段落があるので @masahitojp レビューお願いします!

**Comment by masahitojp** [comment]
お疲れ様です。了解です。

**Comment by masahitojp** [comment]
レビューが遅れてすみません。翻訳おつかれさまでした。
読んでて気づいたのですが、2.X系で全体が翻訳し直しになってるんですね。
(1.X 系と用語がかなり異なる http://www.playframework-ja.org/documentation/1.2/evolutions)

本題に戻ってちょっと訳が気になった箇所のみ列挙しておきます。
- "database schema evolutions" は "データベース・スキーマの進化"の方がよいかなと思います。
  ただ、このmdファイルの題名が "Managing database evolutions"なので今のままでもよいかもしれません。
  多分題名と内容をかけているようにも思えますので。
- "plain old SQL" は "昔ながらのSQL" とした方が訳がしっくりくると思います。
- "(prefered)"は"(より好ましい方法として)"などの方がわかりやすいと思います。

**Comment by wm3** [comment]
レビューありがとうございます！ひとまず、3つ目の (prefered) は反映しました。

で、残りの二つなのですが… 2.0.4 からそのままとってきた物なので少々反映しづらいのが正直な所です。他の方の意見も聞きたい所ではあります。

**Comment by garbagetown** [comment]
> "database schema evolutions" は "データベース・スキーマの進化"の方がよいかなと思います。

スクリプトや機能としてのevolutionsの訳はエボリューションで統一したいと思いますが、この文に限って言えば進化、発展と訳しても良いですね。

> "plain old SQL" は "昔ながらのSQL" 

とても良い訳だと思います！

> 2.0.4 からそのままとってきた物なので少々反映しづらい

今回のレビュー対象は新規に翻訳した段落のみと考えて良いのではないでしょうか。上記二点については2.0から2.0.4まで横展開する必要がありそうなので、別のissueとして管理するのが適当だと思います。

わざわざissueを切るのが手間であれば、見つけてしまった人、気になってしまった人が率先して横展開しつつ修正、2.1ブランチにpullreqを送るのが良いと思います。

上記二点の改善案は反映したいと思うので、鷲田さん、中村さんの手が回らないようであれば私が対応します :smiley:

**Comment by masahitojp** [comment]
pull/reqの件僕の方で引き受けます！とりあえず2.1にpull/reqして、mergeされた後に、他の2.0.0～4に横展開します。
これはこのIssueと関係ないので、別Issueとして起こします。
このIssueについては @wm3 さん側でOKであればcloseして構いません。

**Comment by wm3** [comment]
ありがとうございます。 m(__)m

指摘内容自体は個人的にもいいと思います。やってもらえると助かります。

ここはクローズしますね。
