### ISSUE TITLE
Deploying-CloudFoundry.mdの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#240]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.1/manual/detailledTopics/production/Deploying-CloudFoundry.md

**Comment by wm3** [comment]
新規翻訳なので #358 のレビューをお願いしたいです。 @garbagetown さんですかね…。

**Comment by garbagetown** [comment]
ありがとうございます！

確認しました。ほぼ完璧だと思います。趣味レベルのコメントを #358 に直接記入してみましたのでご確認ください :-)

**Comment by garbagetown** [comment]
azs!!
