### ISSUE TITLE
HTTPServer.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#242]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/detailledTopics/production/HTTPServer.md

**Comment by garbagetown** [comment]
翻訳しました。@wm3 さん、レビューをお願いします！
主に 7c97bcc0c5688ff706fd8457e3d4962b1dc3e6db の内容をご確認ください。

**Comment by wm3** [comment]
確認しました！ほぼ問題無いと思います。

1点だけ、

> ... will rarely give you better performance ...

の所が

> 優れたパフォーマンスが得られることは決してない

となっていますが、「めったに」程度の方が良いかな、と思いました。

**Comment by garbagetown** [comment]
翻訳漏れでした。ありがとうございます！

対応したのでクローズします :smiley:
