### ISSUE TITLE
ProductionConfiguration.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#244]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.1/manual/detailledTopics/production/ProductionConfiguration.md

**Comment by wm3** [comment]
もう少し見たいので GitHub に上げていませんが、翻訳はそこそこ終わっています。一応報告まで。

**Comment by garbagetown** [comment]
了解です :smiley:

**Comment by wm3** [comment]
Pull Request を送りました。
@garbagetown さん、レビューをお願いします。m(__)m

**Comment by garbagetown** [comment]
マージしました。クローズします！
