### ISSUE TITLE
IDE.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#248]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/gettingStarted/IDE.md

**Comment by wm3** [comment]
ひとまずクローズします。

**Comment by wm3** [comment]
返事が遅れてすみません、 48d3868 の修正は確認しました。クローズしても大丈夫でしょうか?

**Comment by garbagetown** [comment]
https://github.com/garbagetown/playdocja/pull/352 でpullreqしている件ですよね。問題なければマージしてクローズしちゃってください。
