### ISSUE TITLE
BuildingFromSource.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#253]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/hacking/BuildingFromSource.md

**Comment by garbagetown** [comment]
翻訳しました。 @mumoshu さん、レビューをお願いします！

主に f06720e97d9bea189db944e028434932af498cce の内容をご確認ください。

**Comment by garbagetown** [comment]
@mumoshu さんお忙しい感じですか？

**Comment by mumoshu** [comment]
すみません！メール見落としてました・・

**Comment by garbagetown** [comment]
お忙しく無ければざっとご確認頂けますか？

**Comment by mumoshu** [comment]
レビューしました。1件だけコメントがあります！

> シェルから Play のソースを初めてチェックアウトします:

原文で使われてる文法も見慣れない感じで自信ありませんが、ここは「シェルから、まずは Play のソースをチェックアウトします」という意味じゃないかと思いました。

読み手が Playのソースをチェックアウトするのが生涯「初めて」かどうかは、これ以降の作業に関係ないですよね。ですから、「まず」とか「初めに」の意味の意味で"first checkout"って言ってるんじゃないかと思います。
とはいえ、原文で使われている文法が（ｒｙ

**Comment by garbagetown** [comment]
なるほど

> first, checkout the play sources from the shell

という感じですね。直して #367 で pullreq しました。確認して問題なければマージしてください :-)

**Comment by garbagetown** [comment]
my pullreq #367 is merged :smiley:
