### ISSUE TITLE
Highlights.mdの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#256]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/Highlights.md

**Comment by garbagetown** [comment]
細かくてすみませんがpullreq送りました。覚えたてでpullreq送りたいだけかもしれません><

ご確認の上、マージとクローズをお願いします :pray:

**Comment by mumoshu** [comment]
マージしましたのでこちらはクローズしておきますね！
あと、プルリを送ることによりIssueが新たに作られるので、今回みたいに既にCloseされた翻訳IssueをReopenする必要はないかも？

**Comment by garbagetown** [comment]
> マージしましたのでこちらはクローズしておきますね！

azs!!

> あと、プルリを送ることによりIssueが新たに作られるので、今回みたいに既にCloseされた翻訳IssueをReopenする必要はないかも？

あ、なるほど。では今後はreopne無しで行きましょう！ありがとうございます :smiley:
