### ISSUE TITLE
JavaInjection.mdの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#277]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/javaGuide/main/inject/JavaInjection.md

**Comment by garbagetown** [comment]
翻訳ありがとうございます！マージしたいので pullreq して頂けないでしょうか。

**Comment by wm3** [comment]
ちょっと暖めすぎましたね…リクエスト送りました！

**Comment by garbagetown** [comment]
merged pullreq #365
