### ISSUE TITLE
日本Playframeworkユーザー会のページを作りたい

### ISSUE THREAD

**Issue by ikeike443** [playframework-ja/translation-project#28]
もしよければ、Playdocjaに一タブ追加させていただいて、日本Playframeworkユーザー会のページを作りたいなあと考えています。

取り急ぎForkしてローカルで作ってみてからPull requestします。

よろしくお願いします。

**Comment by garbagetown** [comment]
どういった内容になりますか？ちょっと思うところがあってgae/jは止めようかと思っているので、例えばsienaモジュールに依存する内容だったりする場合は事前にお知らせ頂ければと思います。

**Comment by ikeike443** [comment]
了解です。結局手が回ってないのですが、gae/jとはかかわりのない部分にはなると思います。
静的ページを作るだけのつもりなので。。

**Comment by garbagetown** [comment]
doorkeeper等のサービスを利用する方向で検討させてください。一旦クローズします。
