### ISSUE TITLE
JavaEbean.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#280]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/javaGuide/main/sql/JavaEbean.md

**Comment by garbagetown** [comment]
翻訳しました。追記された内容が割と重要だったので、 @mumoshu さんレビューをお願いします！

**Comment by mumoshu** [comment]
レビュー遅くなりました :sweat: 

まず、これって 2.0系の方も未翻訳だったんですよね？（パッチに含まれてるので

指摘は以下１件です。

> このヘルパーフィールドはモデルのクエリーを単純化するために使われます。

「単純化」ではなく「簡単化」かなと思いました。

**Comment by garbagetown** [comment]
2.0系は2.0と2.0.1が未訳で、2.0.2〜2.0.4は読み易さのために半角スペースを入れました。

差分を見返してみたら自分でも何がなんだか分からなかったので、次からは鷲田さんのように作業単位毎にコミットを分けます。申し訳ありませんでした :sweat: 

ご指摘頂いた件、alcやexcite翻訳、google翻訳など調べてみたところ、simplifyには「簡素化」という訳が多く、意味としてもしっくり来るので、これで統一しようと思いますが、いかがでしょうか。

**Comment by garbagetown** [comment]
「簡素化」で統一しました。大勢に影響はないと思いますのでクローズします
