### ISSUE TITLE
zentasksの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#287]
https://github.com/garbagetown/playdocja/tree/2.1/documentation/2.1.0/manual/javaGuide/tutorials/zentasks
- JavaGuide1.md
- JavaGuide2.md
- JavaGuide3.md
- JavaGuide4.md
- JavaGuide5.md
- JavaGuide6.md
- JavaGuide7.md

**Comment by garbagetown** [comment]
遅くなりましたが翻訳しました。大量で大変だとは思いますが @wm3 さん、レビューお願いします！

**Comment by wm3** [comment]
ちょっと時間かかるかもしれませんが、了解しました!

**Comment by wm3** [comment]
ちょっと間が空いてしまったので報告を。

まとまった時間ができたのでレビューをしていて、一通りざっと目を通しました。…しかし中々分量が多そうなので、簡単な typo を pull request としてまず送り、間違いや細かなニュアンス等に関してはレビュー機能を使うか個々で pull request を送ろうかと思っています。

**Comment by wm3** [comment]
1-3 までを一通りレビューを通して、 typo と、比較的大きな気になる所を pull request してみました。

実は細かい単語レベルで気になる所もあったのですが、数が多くなってしまうと思ったので pull request ではなくレビュー機能で送ろうかと思います。

**Comment by garbagetown** [comment]
ありがとうございます！すぐにマージできるものはマージしました。

細かいものはレビュー機能でも結構です。よろしくお願いします。

**Comment by wm3** [comment]
JavaGuide1 (b5c5a11) から JavaGuide3 (b0c48e4) の細かい部分で気になった所のレビューを書きました。ちなみに、 JavaGuide2 には気になった所はありませんでした。

**Comment by wm3** [comment]
けっこう時間がかかってしまいましたが、一通りレビューをしました。

JavaGuide 4〜7 に関して気になった点をプルリクエストに上げました。m(__)m

**Comment by garbagetown** [comment]
大量のレビューありがとうございました！頂いたプルリクエストと指摘事項をすべて反映しましたので、クローズします:-)
