### ISSUE TITLE
ScalaAsync.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#302]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.1/manual/scalaGuide/main/async/ScalaAsync.md

**Comment by wm3** [comment]
翻訳しました。修正の多くは Promise -> Future への変換なのですが、少しだけそうでもない部分もあるのでレビューをお願いします。(度々済みませんが @garbagetown さん)

**Comment by garbagetown** [comment]
ばっちりだと思います！
