### ISSUE TITLE
ScalaRouting.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#313]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/scalaGuide/main/http/ScalaRouting.md

**Comment by mumoshu** [comment]
翻訳しました

**Comment by garbagetown** [comment]
typo があったので pullreq 送りました。確認お願いします :pray:

**Comment by mumoshu** [comment]
マージしましたので閉じます！
