### ISSUE TITLE
ScalaSessionFlash.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#314]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.1/manual/scalaGuide/main/http/ScalaSessionFlash.md

**Comment by wm3** [comment]
ほぼ2.0.4との修正が無いのでこちらに直接コミットしました。

ただ少しだけ段落が追加されているので、 @garbagetown さんレビューをお願いします。 m(__)m

**Comment by garbagetown** [comment]
レビューしました！ってお伝えしていませんでしたね。申し訳ありません。

20e7f47 にコメント追記していますので、ご確認ください

**Comment by wm3** [comment]
返事が遅れて済みません…。m(__)m レビューを反映しました。

比較的小さな修正なので、そのままクローズしてしまいます。
