### ISSUE TITLE
ScalaJson.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#316]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/scalaGuide/main/json/ScalaJson.md

**Comment by garbagetown** [comment]
ほぼ新規翻訳でした :sweat_smile:  
@mumoshu さん、レビューお願いします！

**Comment by mumoshu** [comment]
レビューしました！コミットにコメントつけてます。

**Comment by garbagetown** [comment]
azs! pullreq送ったので確認とマージをお願いします。

**Comment by garbagetown** [comment]
my pullreq is merged :smiley:
