### ISSUE TITLE
ScalaJsonCombinators.mdの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#317]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/scalaGuide/main/json/ScalaJsonCombinators.md

**Comment by garbagetown** [comment]
これ、なかなかえげつない量ですね。。。 @mumoshu  さんが未着手でしたら私の方でがんばってみようと思いますが、いかがですか？

**Comment by garbagetown** [comment]
@mumoshu さん、こちらは着手されていますか？

これと巻き取らせて頂いた ScalaJsonTransformer の内容に連続性があって、後者を翻訳するためにこれもある程度読む必要がありました。内容は大体理解したので、もし未着手でしたらこちらも巻き取らせて頂きたいと思います。

**Comment by mumoshu** [comment]
巻き取っていただけると嬉しいです。よろしくお願いします！

**Comment by garbagetown** [comment]
いただきまーす :smiley:

**Comment by garbagetown** [comment]
お待たせしました。翻訳しましたので、 @wm3 さん、レビューをお願いします！

**Comment by wm3** [comment]
レビュー中です。ページの分量が多いため、気になった点も整理しながら進めた方が良い思うので、少しずつプルリクエスト等を出していこうかと思っています。

**Comment by wm3** [comment]
まずは、気になった所で全体的で形式的な物をプルリクエストとして送りました。

#395 #396 になります。

**Comment by wm3** [comment]
二つほどプルリクエストを送りました。 #397 #398 

あと、気になる所として、「ニュアンスとかがこちらと思ったのと違う」と思った部分がいくつか残っているのですが、時間が無くなってしまったので明日お送りします。

**Comment by wm3** [comment]
プルリクエストを送りました。 #399

再度レビューした所、現状で十分だと思ったので、このプルリクエストがクローズされ次第、この issue もクローズしようと思います。

**Comment by wm3** [comment]
お疲れ様でした！
