### ISSUE TITLE
ScalaJsonRequests.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#319]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/scalaGuide/main/json/ScalaJsonRequests.md

**Comment by garbagetown** [comment]
@mumoshu 
勝手なことをして申し訳ありませんが、少し時間ができたので assign を私に変更しました。仕掛かり中の翻訳があったらすぐにご連絡ください。

**Comment by garbagetown** [comment]
翻訳しました。 @mumoshu さん、レビューをお願いします！

主に 4a8f7da の内容をご確認ください。

**Comment by mumoshu** [comment]
翻訳ありがとうございます！
4a8f7da にコメントしました。

**Comment by garbagetown** [comment]
早！ありがとうございます :-)

頂いたコメントに対してさらにコメントしてみました。ご確認ください！

**Comment by mumoshu** [comment]
返信しました！ご確認ください〜

**Comment by garbagetown** [comment]
直しました！クローズしまーす
