### ISSUE TITLE
ScalaJsonTransformers.mdの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#320]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/scalaGuide/main/json/ScalaJsonTransformers.md

**Comment by garbagetown** [comment]
@mumoshu 
これも重いですね。。。 Pascal Viotot の ScalaJsonXxx シリーズを手分けして終わらせたいので、着手中のもの以外、一旦 assign を外して頂けますか？

**Comment by mumoshu** [comment]
外しておきました！

**Comment by garbagetown** [comment]
ありがとうございます！こちらは私の方で進めさせて頂きます！
#317 ScalaJsonCombinators.md と #318 ScalaJsonInception.md はお願いしてよろしいでしょうか？

**Comment by mumoshu** [comment]
はいー。その二つは僕の方で翻訳させて頂きます！

**Comment by garbagetown** [comment]
よろしくお願いします :smiley:

**Comment by garbagetown** [comment]
荒川の河川敷で翻訳してpushしましたｗ @wm3 さん、レビューをお願いします！

**Comment by wm3** [comment]
ScalaJsonCombinators と同様のインデントの修正をしました。 #400

**Comment by garbagetown** [comment]
頂いた #400 のプルリクエストが自動でマージできないようです。すごい数のコミットが表示されるので、なにかおかしいような気がします。GitHub 側の問題かもしれませんが、一度ご確認頂けますか？

**Comment by wm3** [comment]
番号通り Bad Request でしたね…。master への pull request になっていました。

同じ物を #401 で送りました。

**Comment by wm3** [comment]
非常に感覚的な話なのですが、「pick」の訳で、「つまみだす」というのが、あまり馴染みない感じがしてしまいました。

「選び取る(http://ejje.weblio.jp/content/pick から)」か「取り出す(辞書にはありませんが、なじみのある文になりそうです)」でどうでしょう?

その他、個別で気になった点もあったのですが、今夜送ります…。

**Comment by garbagetown** [comment]
JSON を（抽象構文）木に見立てて枝と葉で説明しているので、「摘み取る」なんかもかっこいいですが、ちょっと趣味に走り過ぎですね。「つまみ出す」も趣味で訳したところがあるので改善しましょう。

JsPath を指定する場合は「選び取る」が的を得ていると思いますが、JsValue として取り出す場合などには少し不適切ですね。全体的に無理なく統一感を出せる訳は「取り出す」だと思います。

同じく趣味に走って prune を「刈り取る」と訳しているので、こちらも「取り除く」に変えた方がいいかもしれないです。

**Comment by wm3** [comment]
#402 #403 を送りました…。

ここのドキュメントは直訳しようとするとどうにもならない気がしてきたので、文脈を見て(意訳して)書いてしまっています。

**Comment by wm3** [comment]
ちょっと力つきたので、比較的細かい部分については f744431 にコメントを載せました。

一応、この文章に関しては気になった所は一通り書き出しました。

**Comment by garbagetown** [comment]
9bddcfe で頂いたコメント対応しました。どちらも凡ミスですね。。。お手数お掛けして申し訳ありません。

**Comment by garbagetown** [comment]
pick と prune の件、 5ab0ee7 で対応しました。pullrequest にしようかとも思いましたが、「取り出す」と「取り除く」にしてみたら、とても自然な訳になったので push しました。

ご確認頂いて、問題ないようであればクローズをお願いします。

**Comment by wm3** [comment]
ありがとうございます!

コメントの反映や刈り取るの変更の方も含めて問題無いかと思いました。クローズします。
