### ISSUE TITLE
ScalaTemplates.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#324]
https://github.com/garbagetown/playdocja/blob/master/documentation/2.1/manual/scalaGuide/main/templates/ScalaTemplates.md

**Comment by wm3** [comment]
ほとんど JavaTemplates.md と同じなので、クローズしてしまいます。

https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/javaGuide/main/templates/JavaTemplates.md
