### ISSUE TITLE
ScalaTest.mdの翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#326]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/scalaGuide/main/tests/ScalaTest.md

**Comment by garbagetown** [comment]
@masahitojp さん、こちらの状況はいかがですか？手持ちの issue が終わったので、もし未着手であれば巻き取らせて頂きたいと思います。

**Comment by masahitojp** [comment]
よろしくお願いします。

**Comment by garbagetown** [comment]
翻訳しました。 @masahitojp さん、レビューお願いできますか？お忙しいようでしたら誰かに振ってください。

**Comment by masahitojp** [comment]
OKです。レビューしておきました。 good! closeしてOKです。

**Comment by garbagetown** [comment]
azs!!
