### ISSUE TITLE
User-Groups-around-the-World.mdの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#331]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/User-Groups-around-the-World.md

**Comment by masahitojp** [comment]
翻訳しました

**Comment by garbagetown** [comment]
対応ありがとうございます！以下少しが気になったのでpullreqの練習も兼ねて一部修正してみました。ご確認お願いします :-)
- オリジナルのドキュメントに存在しない記述が追記されている
  - あくまで翻訳プロジェクトなので、ドキュメントが不親切と感じたら、まず本家にpullreq、無事に取り込まれたら翻訳にも反映という流れが良いと思います
- アメリカ -> "U.S.A", イギリス -> "イングランド", フランス -> "フランス" と表記に統一性がない

**Comment by masahitojp** [comment]
> オリジナルのドキュメントに存在しない記述が追記されている

「現状のドキュメントに従って翻訳を行う」ルールということですね。了解です。
まーそもそもこのページって各国のユーザーがノールールで書いていたものだったはずなので、本来翻訳せずにそのまま載せるのが正しいのかもですね。

>    アメリカ -> "U.S.A", イギリス -> "イングランド", フランス -> "フランス" と表記に統一性がない

意図はあってこんな書き方になってます。が、オリジナルのドキュメントに従うのであれば、そもそもこの部分はいらなくなりますね。(原文だと地名だけなので、国名表示もあったほうが親切だと思ったんですが仇になってしまいましたねorz)

**Comment by garbagetown** [comment]
> 「現状のドキュメントに従って翻訳を行う」ルール

そうしたいと思います。叩き台を作っていただいた翻訳ガイドにも追記します。

> 親切だと思ったんですが

そう思うときは多々あるのですが、一度これをやり始めてしまうと例えば「JDK」に「Java Development Kit」と訳注を付けるのか、等と際限が無くなってしまうので、あくまで翻訳に徹したいと思います。

**Comment by masahitojp** [comment]
mergeしました。
