### ISSUE TITLE
ThreadPools.mdの新規翻訳

### ISSUE THREAD

**Issue by masahitojp** [playframework-ja/translation-project#335]
https://github.com/garbagetown/playdocja/blob/2.1/documentation/2.1.0/manual/detailledTopics/configuration/ThreadPools.md

**Comment by masahitojp** [comment]
翻訳した量が多いので @garbagetown さんレビューをお願いします。

**Comment by garbagetown** [comment]
長文翻訳ありがとうございます！レビューしてfix_335でpullreqしましたので、確認してください。

**Comment by masahitojp** [comment]
確認しました。PRありがとうございました。
