### ISSUE TITLE
Migration.mdの修正

### ISSUE THREAD

**Issue by mumoshu** [playframework-ja/translation-project#338]
documentation/2.1/manual/Migration.md

_foo_
*_bar_*
の後に半角スペースを空ける必要がある。

**Comment by masahitojp** [comment]
本家ドキュメント側の問題でしょうか？

**Comment by mumoshu** [comment]
翻訳時のミスです。
忘れないようにIssue化しました！

**Comment by masahitojp** [comment]
なるほど、理解しました。できましたら、MileStoneとTagの設定を行ってくださいー。

**Comment by mumoshu** [comment]
しましたー

**Comment by mumoshu** [comment]
対応しました

**Comment by garbagetown** [comment]
pullreq 送りました。毎度細かくて申し訳ありませんがマージとクローズお願いします。

**Comment by mumoshu** [comment]
マージしましたので閉じます
