### ISSUE TITLE
scalaGuide/advanced/http/ScalaHttpFilters.md

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#385]

**Comment by garbagetown** [comment]
新規翻訳なので @wm3 さん、レビューをお願いします。

前半は特に迷いませんでしたが、 `More powerful filters` の段落の内容があまり理解できていません :sweat:

**Comment by wm3** [comment]
ざっとみた限りではおかしな所は見当たりませんでした。帰ってきてからもう少し見てみます…。

**Comment by wm3** [comment]
細かいレベルのコメントをしておきました。

More Powerful Filters の部分は馴染みのない部分で僕もはっきりとは自信が無いのですが、 見た限りでは誤訳等は無いように読めました。

**Comment by garbagetown** [comment]
ありがとうございました！反映したのでクローズします :smiley:
