### ISSUE TITLE
scalaGuide/main/json/ScalaJsonInception.md

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#389]

**Comment by garbagetown** [comment]
翻訳しました！ @mumoshu さん、レビューをお願いします。

さほど難しくありませんでしたが、追加された部分 d5eebb7 と、2.1.0 も含めて全体的な統一感や見た目の改善を行ってみた c3670e0 を中心にご確認頂ければと思います。

今月中に 2.1.1 を公開したいのですが、ぼくが 07/28〜07/31 まで動けないので、できれば 07/26 を目処に確認頂ければと思います。お忙しいようでしたら他の方に振りますので、その旨コメントください :octocat:

**Comment by mumoshu** [comment]
コメントしました！よろしくお願いします

**Comment by garbagetown** [comment]
それぞれ対応しました。確認をお願いします :smiley:

**Comment by mumoshu** [comment]
確認しました。
ご対応ありがとうございます！
