### ISSUE TITLE
コードのシンタックスハイライトがされてない

### ISSUE THREAD

**Issue by bigwheel** [playframework-ja/translation-project#492]
http://www.playframework.com/documentation/2.0.8/Enumeratees
ではコードがシンタックスハイライトされていますが、日本語版では
http://www.playframework-ja.org/documentation/2.0.8/Enumeratees
のようにすべて灰色になっています。

そのページのHTMLしか見てませんが、本家では

``` html
<style type="text/css">
@import "/assets/stylesheets/prettify.css";
</style>
```

となっているところが日本語版ですと

``` html
> <style type="text/css">
> @import "http://twitter.github.com/bootstrap/assets/js/google-code-prettify/prettify.css";
> </style>
```

になっているので、そのへんが原因のようです。

**Comment by garbagetown** [comment]
ご指摘ありがとうございます。次回リリースで対応します。

**Comment by garbagetown** [comment]
いろいろ問題があって思っていたより大変。

まず twitter.github.com から prettify.js と prettify.css を落としてきているところは当該 URL が既に存在しないので自前で持つように変更しないとだめ。
- https://github.com/garbagetown/playdocja/blob/2.2.0/app/views/main.html#L187
- https://github.com/garbagetown/playdocja/blob/2.2.0/app/views/Documentation/page.html#L90

つぎにハイライトするコードの種類を指定してやらないといけない。prettify.js がよきに計らってくれるらしいけど本家は HTML5 スタイルで言語を指定している
- [Javascript code prettifier](http://google-code-prettify.googlecode.com/svn/trunk/README.html)

```
<pre class="prettyprint"><code class="language-java">package controllers;

import play.*;
import play.mvc.*;

public class Application extends Controller {

    public static Result index() {
        return ok(&quot;It works!&quot;);
    }

}</code></pre>
```

コードを外部から読み込んでいる場合は #645 の対応に手を加えて、読み込んでいるファイルの拡張子を `code class` に埋め込んでやれば良さそう。

従来のコードを markdown に埋め込んでいる場合は [sirthias/pegdown](https://github.com/sirthias/pegdown) のプラグインを書く必要があるっぽい。[pegdown プラグイン](https://github.com/sirthias/pegdown/commits/master/src/main/java/org/pegdown/plugins/PegDownPlugins.java) は 1.3 くらいからの機能なので最新の 1.4.2 に依存するように変更しないとだめ。
- https://github.com/garbagetown/playdocja/blob/2.2.0/conf/dependencies.yml#L7

**Comment by garbagetown** [comment]
done

**Comment by garbagetown** [comment]
generated html was broken when the .md source has code block syntax using triple backtick inline.

**Comment by garbagetown** [comment]
done
