### ISSUE TITLE
controllers.textile garbling

### ISSUE THREAD

**Issue by mizuo** [playframework-ja/translation-project#5]
https://github.com/garbagetown/playdocja/blob/10f14c74dfcde3f0f7ab210275cb48c0c8ce3af7/documentation/1.2.1/manual/controllers.textile

I can't read this file because of the garbling.

---

コントローラの説明ページが文字化けしています。

**Comment by garbagetown** [comment]
直しました。ご報告ありがとうございました:-)

**Comment by mizuo** [comment]
thanks.

ご対応いただきありがとうございました。
日本語情報のおかげで、すばらしいフレームワークに出会う事ができました。
感謝しています。

英語情報しか無かったら、多分途中で挫折していたところです…。
