### ISSUE TITLE
@[global](...) 形式で文章に埋め込まれたコードが表示されない

### ISSUE THREAD

**Issue by wm3** [playframework-ja/translation-project#645]
Play 2.2 のドキュメントでは 「@[global](...)」 という記法でコードを外部のファイルに出している事がありますが (#560 等) で、翻訳サイトではそのまま表示されてしまうようです。

@garbagetown さん曰く、対応が必要との事。

https://twitter.com/garbagetown/status/443531071309619200

**Comment by garbagetown** [comment]
done but current version does not highlights the code. It'll fix after #492 is closed.

**Comment by garbagetown** [comment]
The codes does not extracted when the mark has indent spaces.

And there is more special mark like '//###replace:'.

**Comment by garbagetown** [comment]
done :smiley:

**Comment by garbagetown** [comment]
The unexpected codes are also extracted when they had the same id prefix, like "some-id" and "some-id-suffix".

**Comment by garbagetown** [comment]
The codes surrounded with heredoc style mark like '""" #id' and '#id """' are not extracted.

**Comment by garbagetown** [comment]
some lines are displayed without spaces like below.

```
importplay.GlobalSettings;
importplay.api.mvc.EssentialFilter;
importplay.filters.csrf.CSRFFilter;

publicclass Global extends GlobalSettings {
...
```

see also:
- http://www.playframework.com/documentation/2.2.0/JavaCsrf
- http://localhost:9000/documentation/2.2.0/JavaCsrf
- http://localhost:9000/documentation/2.2.0/ScalaCsrf

**Comment by garbagetown** [comment]
inline 3 backtick syntax is broken. see 
- http://localhost:9000/documentation/2.2.0/JavaInjection

**Comment by garbagetown** [comment]
have to `//###insert` syntax. see
- http://localhost:9000/documentation/2.2.0/ScalaActions

**Comment by garbagetown** [comment]
havo to support `#Display` syntax, see
- http://localhost:9000/documentation/2.2.0/ScalaRouting

**Comment by garbagetown** [comment]
have to support the codes in blockqoute. see 
- http://localhost:9000/documentation/2.2.0/ScalaForms
- http://localhost:9000/documentation/2.2.0/ScalaFormHelpers

**Comment by garbagetown** [comment]
we don't need to fix above bugs coz our translations come to be included to playframework.com and to be parsed with the playframwork.com's special syntax parser.
