### ISSUE TITLE
index.textile翻訳

### ISSUE THREAD

**Issue by garbagetown** [playframework-ja/translation-project#66]
1.2以降すべてのバージョンのindex.texileが翻訳されていない

**Comment by masahitojp** [comment]
↓1.2.2のindex.textileは1.1以前のものであるってことですか？

http://playdocja.appspot.com/documentation/1.2.2/index

**Comment by garbagetown** [comment]
あれ？1.2.3用のブランチを切ったときには未訳だったような気がするのですがいつの間にリリースされていたんだろう？
https://github.com/garbagetown/playdocja/blob/1.2.3/documentation/1.2.2/manual/index.textile

ぼく自身gitのブランチの操作が怪しいのでなにかミスったかもしれません。

今回はkitoranaokiさんが（二度手間になってしまったかもしれませんが）翻訳してくださったので結果オーライですが、やっぱり作業手順とか決めないとまずいですね :-(

**Comment by masahitojp** [comment]
今後を考えると作業手順とかをまとめたいですね。
とりあえずgithubのwikiを使いませんか？こんな流れで翻訳してたとかを書いとくといろいろはかどると思います。

あとは、翻訳専用のコミュニケーションが欲しいですね。Skype チャット or Lingrでも使いませんか？

**Comment by garbagetown** [comment]
あ、githubのwikiはとてもいいですね。まずは今日の昼休みにでも叩きを作ってみます。

翻訳者用のオンラインコミュニケーションはskypeチャットがいいと思いますが、なかなかタイミングが合わないと思うので、オフラインのコミュニケーション手段も欲しいです。
個人的にはplay_jaのMLが過疎化していてもったいないので使っちゃえばいいかなと思っています。

**Comment by kitoranaoki** [comment]
1.2.3 と 1.2.4 とで差分がなく、また 1.2.3 で翻訳済みのものがブランチ (1.2.4) に存在するためクローズします。
