### ISSUE TITLE
リンク切れです

### ISSUE THREAD

**Issue by hidekez** [playframework-ja/translation-project#93]
初めて投稿します。
http://playdocja.appspot.com/documentation/1.2.3/libs#FunctionalprogrammingwithJava
こちらのページにあるページ内部リンクが切れてるようです。
なお、他のページは特に確認してはいませんので、同様な問題があるかどうかは存じておりません。

**Comment by kitoranaoki** [comment]
連絡ありがとうございます。
すぐには無理かもしれませんが修正いたします。

**Comment by kitoranaoki** [comment]
本家でリンク先を確認したところ Javadoc へのリンクでした。playdocja では Javadoc を持っていないので対応するかどうかを決める必要があります。

**Comment by garbagetown** [comment]
playdocja では javadoc を持たないこととします。本家の javadoc を別タブで参照するよう実装を修正します。
